import { CaseStudy } from "@/lib/schema";

export const caseStudies: CaseStudy[] = [
  {
    id: "pega-insurance-claims-automation",
    slug: "pega-insurance-claims-automation",
    title: "Global Insurer Automates 70% of Claims Processing with Pega Infinity",
    client: "Tier-1 Global Property & Casualty Insurer",
    industry: "Insurance",
    serviceCategory: "Pega Development & Testing",
    heroHeadline: "Modernizing Legacy Claims Settlement with Pega Case Management & Next-Best-Action",
    summary: "NForce One architected a unified Pega Infinity claims orchestration engine, replacing four legacy mainframe systems and automating first-notice-of-loss (FNOL) through adjudication.",
    metrics: [
      { value: "70%", suffix: "Automated", label: "Touchless Claims Adjudication" },
      { value: "14", suffix: "Days to 2 Hrs", label: "Cycle Time Reduction" },
      { value: "$18.5M", suffix: "Saved", label: "Annual Operational Savings" },
    ],
    challenge: [
      "The client operated 4 legacy policy and claims systems across North America, causing severe communication silos and slow claim resolution.",
      "Average claim settlement cycle took 14 business days with over 8 manual handoffs per claim.",
      "Customer satisfaction (CSAT) scores were declining due to lack of real-time status visibility across digital channels.",
      "High operational overhead and compliance audit vulnerability due to fragmented manual paper logs.",
    ],
    solution: [
      "Architected an enterprise Pega Infinity application utilizing Pega Situational Layer Cake architecture to accommodate state-by-state regulatory variations.",
      "Integrated Pega Customer Decision Hub (CDH) to evaluate fraud indicators and determine optimal settlement paths in real time.",
      "Engineered automated PegaUnit and Scenario Testing regression suites into the CI/CD pipeline, ensuring zero release regressions.",
      "Built a modern self-service claimant web portal connected securely via Pega Constellation and REST APIs.",
    ],
    architecturePoints: [
      "Pega Infinity 23 running on Pega Cloud with multi-region failover",
      "Kafka event streaming for real-time telematics and FNOL event ingestion",
      "Secure bidirectional REST integrations with Guidewire PolicyCenter and SAP GL",
      "Pega Deployment Manager automated release pipeline with 94+ Guardrail compliance",
    ],
    impact: [
      "70% of standard auto and property claims now settle touchlessly within 2 hours.",
      "Customer CSAT scores increased by 38 points within 6 months of rollout.",
      "Reduced underwriting compliance audit prep time from 3 weeks to 15 minutes.",
      "Platform scaled effortlessly to handle a 300% surge during peak regional weather events.",
    ],
    testimonial: {
      quote: "NForce One's Pega architects brought an unparalleled level of technical mastery and operational rigor. They didn't just deliver software; they completely transformed our claims delivery model.",
      author: "Chief Information Officer",
      role: "Global Property & Casualty Group",
    },
    featured: true,
  },
  {
    id: "fintech-realtime-data-lakehouse",
    slug: "fintech-realtime-data-lakehouse",
    title: "FinTech Leader Builds Sub-Second Real-Time Lakehouse for Fraud Detection",
    client: "Global Digital Payments & Card Issuing Platform",
    industry: "Banking & Financial Services",
    serviceCategory: "Big Data & Data Analytics",
    heroHeadline: "Scaling High-Throughput Event Ingestion to 50,000 TPS with Apache Spark & Delta Lake",
    summary: "Replaced an overwhelmed batch data warehouse with an ultra-low-latency streaming lakehouse on Databricks and Kafka, enabling instant transaction anomaly detection.",
    metrics: [
      { value: "50k", suffix: "TPS", label: "Peak Ingestion Throughput" },
      { value: "85ms", suffix: "Latency", label: "Real-Time Risk Scoring" },
      { value: "55%", suffix: "Cost Cut", label: "Cloud Compute Savings" },
    ],
    challenge: [
      "Legacy nightly batch ETL caused an 8-hour latency in reporting, allowing fraudulent transactions to escape detection until the following day.",
      "Compute costs were spiraling out of control due to inefficient ad-hoc SQL cluster provisioning.",
      "Engineering teams lacked data lineage and automated data quality checks, causing frequent dashboard breakdowns.",
    ],
    solution: [
      "Engineered a real-time event streaming pipeline using Apache Kafka and Apache Flink for continuous micro-batching.",
      "Deployed a unified Medallion Architecture (Bronze/Silver/Gold) on Databricks Delta Lake.",
      "Implemented dbt semantic models and automated data assertions using Great Expectations.",
      "Built low-latency Power BI dashboards and automated alerting endpoints for executive risk teams.",
    ],
    architecturePoints: [
      "Apache Kafka distributed clusters deployed on AWS EKS",
      "Databricks Lakehouse with Delta Live Tables and automated auto-scaling",
      "Terraform IaC managing all cloud security groups, IAM roles, and storage buckets",
      "Prometheus & Grafana observability monitoring data freshness and throughput SLOs",
    ],
    impact: [
      "Prevented an estimated $12M in fraudulent transactions during the first quarter of production.",
      "Reduced end-to-end data latency from 8 hours to under 85 milliseconds.",
      "Cut monthly AWS cloud data infrastructure spend by 55% via optimized cluster lifecycle policies.",
    ],
    testimonial: {
      quote: "The big data engineering prowess of NForce One allowed us to scale from proof-of-concept to 50,000 transactions per second without a single production hitch.",
      author: "VP of Data Engineering",
      role: "Global Payments Platform",
    },
    featured: true,
  },
  {
    id: "healthcare-cloud-devops-modernization",
    slug: "healthcare-cloud-devops-modernization",
    title: "Healthcare Provider Achieves Zero-Downtime Multi-Cloud Kubernetes & HIPAA Compliance",
    client: "National Healthcare Network & Telehealth Provider",
    industry: "Healthcare & Life Sciences",
    serviceCategory: "DevOps & Cloud Engineering",
    heroHeadline: "Automating HIPAA-Compliant Infrastructure as Code & Continuous Delivery Across 400+ Clinics",
    summary: "Modernized brittle on-premise clinical infrastructure into secure, automated AWS EKS Kubernetes clusters with GitOps, continuous compliance, and automated DR.",
    metrics: [
      { value: "99.999%", suffix: "Uptime", label: "Clinical System Availability" },
      { value: "100%", suffix: "Automated", label: "Infrastructure as Code (IaC)" },
      { value: "4x", suffix: "Faster", label: "Release Cadence" },
    ],
    challenge: [
      "Manual server provisioning created 6-week delays for new clinic onboarding and telehealth service rollouts.",
      "Strict HIPAA compliance audits required weeks of manual screenshot gathering and log consolidation.",
      "Monolithic application deployments required scheduled Sunday downtime, disrupting 24/7 urgent care centers.",
    ],
    solution: [
      "Architected multi-region AWS EKS Kubernetes clusters with automated pod auto-scaling and zero-downtime blue/green rollouts.",
      "Codified 100% of infrastructure in modular Terraform with automated Checkov security compliance scanning.",
      "Configured ArgoCD GitOps pipelines for transparent, auditable, and automated application deployments.",
      "Implemented centralized HashiCorp Vault secret management and immutable audit trails.",
    ],
    architecturePoints: [
      "AWS EKS with Karpenter intelligent node auto-provisioning",
      "ArgoCD GitOps deployment engine synced with GitHub enterprise repos",
      "OpenTelemetry, Datadog APM, and AWS CloudWatch centralized compliance logs",
      "HIPAA/HITRUST hardened container baseline images with daily vulnerability scans",
    ],
    impact: [
      "Zero minutes of unplanned downtime across 400+ connected medical centers over 18 months.",
      "New clinic digital onboarding time reduced from 6 weeks to 40 minutes.",
      "Achieved 100% clean HIPAA compliance audit score with automated compliance evidence generation.",
    ],
    testimonial: {
      quote: "NForce One delivered a masterclass in enterprise DevOps. Our developers now deploy with absolute confidence, and our compliance posture has never been stronger.",
      author: "Chief Technology Officer",
      role: "National Healthcare Network",
    },
    featured: true,
  },
  {
    id: "retail-ai-customer-engagement",
    slug: "retail-ai-customer-engagement",
    title: "Omnichannel Retailer Boosts Conversion by 34% with Generative AI Product Advisors",
    client: "Enterprise Luxury & Lifestyle Retail Group",
    industry: "Retail & eCommerce",
    serviceCategory: "Artificial Intelligence & Web Development",
    heroHeadline: "Deploying Enterprise RAG & Autonomous Commerce AI across 2.5M Monthly Active Shoppers",
    summary: "Architected a custom Retrieval-Augmented Generation (RAG) conversational commerce engine and headless Next.js frontend, personalizing recommendations in real time.",
    metrics: [
      { value: "+34%", suffix: "Increase", label: "E-Commerce Checkout Rate" },
      { value: "4.8/5", suffix: "CSAT", label: "AI Advisor Satisfaction Score" },
      { value: "<250ms", suffix: "Response", label: "Vector Search & Retrieval" },
    ],
    challenge: [
      "Complex catalog of 80,000+ SKUs resulted in high search abandonment and customer support tickets.",
      "Generic keyword search failed to understand intent or styling nuances.",
      "Slow legacy storefront suffered from 4-second load times and poor mobile conversion.",
    ],
    solution: [
      "Developed a custom RAG pipeline using Pinecone vector database and Claude 3.5 Sonnet fine-tuned on luxury brand catalogs.",
      "Engineered a lightning-fast headless Next.js 15 web storefront with edge rendering and optimized Core Web Vitals.",
      "Integrated autonomous product compatibility checking directly into the shopping cart workflow.",
    ],
    architecturePoints: [
      "Next.js 15 App Router hosted on Vercel with global Edge Middleware",
      "Hybrid Vector & Keyword search running on Pinecone and Elasticsearch",
      "FastAPI microservice backend orchestrating model inference with strict guardrails",
      "Real-time inventory synchronization with SAP S/4HANA ERP via Kafka",
    ],
    impact: [
      "Online revenue increased by $14.2M in the first 90 days after platform launch.",
      "Search abandonment dropped by 52%, with average session duration doubling.",
      "Storefront achieved a 99 Lighthouse performance score with sub-second page loads globally.",
    ],
    featured: false,
  },
];
